name: todo_list
description: "A Flutter MVVM Todo App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9

  # --- NETWORK & API ---
  dio: ^5.9.2

  # --- STATE MANAGEMENT & DI ---
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  get_it: ^9.2.1

  # --- LOCAL STORAGE ---
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  path: ^1.9.1

  # --- UTILITIES ---
  intl: ^0.20.2
  equatable: ^2.0.8
  json_annotation: ^4.11.0

  # --- NOTIFICATIONS ---
  flutter_local_notifications: ^21.0.0

  # --- UI COMPONENTS ---
  flutter_spinkit: ^5.2.2

  #--- UI Splash ---
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.2

  # --- I18N ---
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  flutter_localizations:
    sdk: flutter

  # --- FONTS / SVG / MEDIA (demo resources) ---
  flutter_svg: ^2.3.0
  audioplayers: ^6.6.0
  video_player: ^2.11.1
  chewie: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- CODE GENERATION ---
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  pigeon: ^26.3.2
  json_serializable: ^6.13.0
  flutter_gen_runner: ^5.14.1
  slang_build_runner: ^4.14.0

# --- FLUTTER_GEN CONFIG ---
flutter_gen:
  output: lib/gen/
  line_length: 80
  assets:
    enabled: true
  fonts:
    enabled: true
  integrations:
    flutter_svg: true  # bật cho SVG (cần package flutter_svg — đã có)

flutter_native_splash:
  color: "#4CAF50"
  android: true
  ios: true
  
  android_12:
    color: "#4CAF50"
    image: assets/images/logo.png
    icon_background_color: "#4CAF50"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
