// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct UserPigeon {
  var name: String? = nil
  var email: String? = nil
  var password: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserPigeon? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let email: String? = nilOrValue(pigeonVar_list[1])
    let password: String? = nilOrValue(pigeonVar_list[2])

    return UserPigeon(
      name: name,
      email: email,
      password: password
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      email,
      password,
    ]
  }
}

private class UserApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return UserPigeon.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class UserApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? UserPigeon {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UserApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UserApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UserApiPigeonCodecWriter(data: data)
  }
}

class UserApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = UserApiPigeonCodec(readerWriter: UserApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UserNativeApi {
  func saveUserToNative(user: UserPigeon) throws
  func getUserFromNative() throws -> UserPigeon
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UserNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { UserApiPigeonCodec.shared }
  /// Sets up an instance of `UserNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UserNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let saveUserToNativeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.todo_list.UserNativeApi.saveUserToNative\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveUserToNativeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let userArg = args[0] as! UserPigeon
        do {
          try api.saveUserToNative(user: userArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveUserToNativeChannel.setMessageHandler(nil)
    }
    let getUserFromNativeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.todo_list.UserNativeApi.getUserFromNative\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserFromNativeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUserFromNative()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUserFromNativeChannel.setMessageHandler(nil)
    }
  }
}
